spring:
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_event
    username: postgres
    password: cNBxF5Ang977BPz7kUr2jHHBMu6bQfnh
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: postgres

logging:
  level:
    org.springframework.security: trace

server:
  port: 8080
